pipeline {
    agent any

    parameters {
        choice(name: 'browser', choices: ['chrome', 'edge'], description: 'Select browser')
        choice(name: 'TEST_TYPE', choices: ['@Smoke', '@Regression'], description: 'Suite')
    }

    triggers {
        parameterizedCron('30 23 * * * %browser=edge;TEST_TYPE=@Regression')
    }

    stages {

        stage('Build') { 
            steps {
                bat 'mvn clean compile'
            }
        }
        
        

     stage('Test') {
		environment {
    AMAZON_CREDENTIALS = credentials('amazon_valid_user_01')
}
		
    steps {
       bat 'mvn test -Dbrowser=%browser% -Dcucumber.filter.tags=%TEST_TYPE%'
    }
}
    } 

    post {
        always { 
			
			
			
			script {
    def metricsFile = 'target/retry-metrics.properties'

    if (fileExists(metricsFile)) {

    def metrics = readProperties file: metricsFile

    echo "📊 Retry Metrics File Found: ${metricsFile}"
    echo "📊 Retry Metrics: ${metrics}"

    env.RETRY_EXECUTED = metrics['retryExecuted'] ?: '0'
    env.RECOVERED_BY_RETRY = metrics['recoveredByRetry'] ?: '0'
    env.FINAL_FAILURES = metrics['finalFailures'] ?: '0'
}else {
        env.RETRY_EXECUTED = '0'
        env.RECOVERED_BY_RETRY = '0'
        env.FINAL_FAILURES = '0'
    }
}
			
			
			
            testNG(
    reportFilenamePattern: 'target/surefire-reports/testng-results.xml',
    escapeExceptionMsg: true,
    escapeTestDescp: true,
    showFailedBuilds: true
)
            archiveArtifacts artifacts: 'target/*.html', allowEmptyArchive: true
            archiveArtifacts artifacts: 'target/screenshots/**', allowEmptyArchive: true

            publishHTML([
                reportDir: 'target',
                reportFiles: 'ExtentReport_*.html',
                reportName: 'Extent Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])

            publishHTML([
                reportDir: 'target',
                reportFiles: 'cucumber-report-*.html',
                reportName: 'Cucumber Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])

         emailext(
    to: 'kaushikmayank961@gmail.com',
    subject: "${currentBuild.currentResult}: Automation Report - Build #${env.BUILD_NUMBER}",
    mimeType: 'text/html',
    body: """
    <h2>🚀 Automation Execution Report</h2>

    <p><b>Job:</b> ${env.JOB_NAME}</p>
    <p><b>Build:</b> #${env.BUILD_NUMBER}</p>

    <p><b>Status:</b>
        <span style="color:${currentBuild.currentResult == 'SUCCESS' ? 'green' : 'red'};">
            <b>${currentBuild.currentResult}</b>
        </span>
    </p>

    <p>
        <b>Browser:</b> ${params.browser}
        &nbsp; | &nbsp;
        <b>Suite:</b> ${params.TEST_TYPE}
    </p>

    <hr>

    <h3>📊 Test Summary</h3>

    <table border="1" cellpadding="8" cellspacing="0">
        <tr>
            <th>Metric</th>
            <th>Count</th>
        </tr>
        <tr>
            <td>Total Tests</td>
            <td>\${TEST_COUNTS,var="total"}</td>
        </tr>
        <tr>
            <td>Passed</td>
            <td>\${TEST_COUNTS,var="pass"}</td>
        </tr>
        <tr>
            <td>Failed</td>
            <td>\${TEST_COUNTS,var="fail"}</td>
        </tr>
        <tr>
            <td>Skipped</td>
            <td>\${TEST_COUNTS,var="skip"}</td>
        </tr>
    </table>

    <h3>🔄 Retry Summary</h3>

    <table border="1" cellpadding="8" cellspacing="0">
        <tr>
            <th>Metric</th>
            <th>Result</th>
        </tr>
        <tr>
            <td>Retry Executed</td>
            <td>${env.RETRY_EXECUTED == '1' ? 'Yes' : 'No'}</td>
        </tr>
        <tr>
            <td>Recovered by Retry</td>
            <td>${env.RECOVERED_BY_RETRY}</td>
        </tr>
        <tr>
            <td>Final Failures</td>
           <td>${env.FINAL_FAILURES}</td>
        </tr>
    </table>

    <h3>❌ Failure Details</h3>

    <p>
        Detailed exception, failed step, source line and stack trace
        are available in the Jenkins Console Log and Cucumber Report.
    </p>

    <h3>📄 Reports & Artifacts</h3>

    <p>
        🔹 <a href="${env.BUILD_URL}Extent_20Report/">
            Extent Report
        </a>
    </p>

    <p>
        🔹 <a href="${env.BUILD_URL}Cucumber_20Report/">
            Cucumber Report
        </a>
    </p>

    <p>
        🔹 <a href="${env.BUILD_URL}console">
            Console Log
        </a>
    </p>

    <p>
        🔹 Screenshots are available in Jenkins Build Artifacts.
    </p>

    <hr>

    <p>
        <b>Automation CI/CD Report</b><br>
        Generated by Jenkins
    </p>
    """,
    attachmentsPattern: 'target/ExtentReport_*.html',
    attachLog: true
)
        }
    }
}